apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: server
spec:
  replicas: 1
  template:
    spec:  
      containers:
      - name: server
        resources:
          requests:
            cpu: 100m
            memory: 200Mi

